### ISSUE TITLE
Visual Studio crashes when trying to select PID or Command Line as column

### ISSUE THREAD

**Issue by julia-horvath** [karpach/debug-attach-manager#13] opened 2021-01-07 18:41 UTC
Hi,

I'm using VS 2019 version 16.7.4 and when I try to select any of the additional columns the whole process crashes. In the event viewer I found there was an ArgumentException, but not much more details.

**Comment by debalin** [comment] 2021-04-21 03:22
I am seeing the same thing on VS 2019 Professional version 16.8.2.

**Comment by karpach** [comment] 2021-04-29 17:06
I can't reproduce this in my VS 2019 16.8.4. Can you try the new version that I just released?

Also, can you try to run it in fresh VS Experimental instance:

<Visual studio installation path>\Common7\IDE\devenv.exe" /RootSuffix Exp

I am wondering if this extension conflicts with some other extensions.

**Comment by debalin** [comment] 2021-05-25 21:16
I tried on 16.9.4, both on experimental mode (as you suggested) and normally, and selecting the Command Line column to be displayed crashes VS in both cases.

**Comment by karpach** [comment] 2021-07-12 17:26
Hi, 

I added try/catch with logging to the column selection code. Can you try the attached version?

The search %APPDATA% for debug-attach-log-*.txt file. 

Example, debug-attach-log-20210712.txt

[DebugAttachHistory.zip](https://github.com/karpach/debug-attach-manager/files/6803249/DebugAttachHistory.zip)

**Comment by debalin** [comment] 2021-08-11 01:04
I tested with the attached VSIX, and after selecting the Command Line and clicking OK, it does not do anything (assuming that you are catching the exception, logging it and silently ignoring with provided VSIX). Here's the debug log. 

```txt
2021-08-10 16:48:56.906 -07:00 [FTL] Failed to update selected columns.
System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Shell.Settings.ShellWritableSettingsStore.SetBoolean(String collectionPath, String propertyName, Boolean value)
   at Karpach.DebugAttachManager.Properties.Settings.Save() in c:\SourceCode\debug-attach-manager\DebugAttachHistory\Properties\Settings.cs:line 146
   at Karpach.DebugAttachManager.SelectedColumns.Save(Object sender, RoutedEventArgs e) in c:\SourceCode\debug-attach-manager\DebugAttachHistory\SelectedColumns.xaml.cs:line 47

```

**Comment by karpach** [comment] 2021-10-14 21:29
Thank you for reporting. I just released the update for the extension. The issue should be fixed.

**Closed** 2021-12-22 17:26 UTC
Labels: bug
